add Card style for all champions
WildCodeSchool/2023-02-Orleans-Spe-P3-A pull request #26
Opened 2023-03-31 10:32 UTC by NefytZ

- add style card for champions

2023-03-31 10:43 UTC, greegouze submitted a review, later dismissed

2023-03-31 12:14 UTC, YDrogen requested changes
Mauvais nom de branche
devrait être: `feature/champion-card`

2023-03-31 12:14 UTC, YDrogen commented on src/components/CardChampions.jsx
> +import { Link } from '@chakra-ui/react';
2 imports du même package, à fusionner

2023-03-31 12:14 UTC, YDrogen commented on src/components/CardChampions.jsx
> +import PropTypes from 'prop-types';
Ne pas oublier d'installer le package

2023-03-31 12:14 UTC, YDrogen commented on src/components/CardChampions.jsx
> +function CardChampions({ champion }) {
Le nom du component au singulier, vu qu'il s'agit d'un seul champion par card
-> `ChampionCard`

2023-03-31 12:14 UTC, YDrogen commented on src/components/ListChampions.jsx
> +    fetch('https://ddragon.leagueoflegends.com/cdn/13.6.1/data/en_US/champion.json')
```suggestion
    fetch('//ddragon.leagueoflegends.com/cdn/13.6.1/data/en_US/champion.json')
```
Permet au navigateur de choisir automatiquement `https` ou `http`

2023-03-31 12:14 UTC, YDrogen commented on src/components/ListChampions.jsx
> +    <div style={{ display: 'flex', justifyContent: 'center', flexWrap: 'wrap' }}>
Peut être une `Box` ou `Flex`
https://chakra-ui.com/docs/components/flex

2023-03-31 12:16 UTC, NefytZ commented on src/components/ListChampions.jsx
> +    <div style={{ display: 'flex', justifyContent: 'center', flexWrap: 'wrap' }}>
Oui de base j'avais mis flex mais je sais pas pourquoi les images n'apparaissait plus donc j'ai changer

2023-03-31 12:23 UTC, NefytZ commented on src/components/ListChampions.jsx
> +    fetch('https://ddragon.leagueoflegends.com/cdn/13.6.1/data/en_US/champion.json')
👍🏼

2023-03-31 15:30 UTC, greegouze approved these changes

2023-04-03 07:51 UTC, YDrogen requested changes
La branche n'a pas le bon nom `feature/champion-card`

2023-04-03 07:51 UTC, YDrogen commented on package.json
> +    "proptypes": "^1.1.0",
Ce n'est pas le bon package : `prop-types`

2023-04-03 09:19 UTC, closed without merging