created search bar in home page
WildCodeSchool/2023-02-Orleans-Spe-P3-A pull request #31
Opened 2023-04-05 15:04 UTC by Alexis-Thibault

2023-04-05 15:06 UTC, greegouze approved these changes

2023-04-05 15:27 UTC, Richarddesnoues approved these changes

2023-04-06 07:32 UTC, YDrogen requested changes

2023-04-06 07:32 UTC, YDrogen commented on src/components/SearchBar.jsx
> +  }, []);
Il manque la fonction cleanup avec le `AbortController`

2023-04-06 07:32 UTC, YDrogen commented on src/components/SearchBar.jsx
> +        />
Il manque encore la petite ligne `value` :(

2023-04-06 07:32 UTC, YDrogen commented on src/pages/Home.jsx
> +            B2G.<span style={{ color: 'rgb(208, 168, 92)' }}>JS</span>
```jsx
<span color='#d0a85c'>
```
Il faut éviter le style inline quand c'est possible

2023-04-06 13:43 UTC, YDrogen requested changes

2023-04-06 14:05 UTC, greegouze approved these changes

2023-04-07 13:27 UTC, YDrogen requested changes

2023-04-07 13:37 UTC, Richarddesnoues approved these changes

2023-04-07 14:27 UTC, YDrogen approved these changes

2023-04-07 14:27 UTC, YDrogen requested changes

2023-04-07 14:27 UTC, YDrogen commented on src/assets/images/BackgroundImg.png
nom de l'image en minuscule/kebab-case (désolé j'avais pas vu avant)

2023-04-07 14:40 UTC, greegouze approved these changes

2023-04-07 17:10 UTC, YDrogen approved these changes

2023-04-07 17:10 UTC, merged