Feature/slogan
WildCodeSchool/2023-02-Orleans-Spe-P3-A pull request #46
Opened 2023-04-12 20:59 UTC by greegouze

2023-04-12 21:09 UTC, Alexis-Thibault requested changes

2023-04-12 21:09 UTC, Alexis-Thibault commented on src/pages/Home.jsx
> +  const text1 = 'B2G.JS !!';
{'B2G.JS !!'} je crois ?

2023-04-13 07:26 UTC, Alexis-Thibault submitted a review, later dismissed

2023-04-13 07:52 UTC, YDrogen requested changes

2023-04-13 07:52 UTC, YDrogen commented on src/pages/Home.jsx
> +  const typingText1 = useTypewriter(text1);
```suggestion
  const typingText1 = useTypewriter('B2G.JS !!');
```
👀

2023-04-13 07:59 UTC, Alexis-Thibault approved these changes

2023-04-13 08:04 UTC, YDrogen approved these changes

2023-04-13 08:04 UTC, merged